github.com:
    users:
        sethCodesSometimes:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: sethCodesSometimes
